# Generated by Django 3.2.5 on 2022-06-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zartekApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='creationDate',
        ),
    ]
