# Generated by Django 3.2.5 on 2022-06-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zartekApp', '0002_remove_posts_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dislike',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
